BOARD_SIZE = 640
SQUARE_SIZE = BOARD_SIZE // 8
RIGHTBAR_WIDTH = 200
LEFTBAR_WIDTH = 60
TOPBAR_HEIGHT = 60
BOTTOMBAR_HEIGHT = 40
MINI_PANEL_WIDTH = 240

WIDTH = LEFTBAR_WIDTH + BOARD_SIZE + RIGHTBAR_WIDTH + MINI_PANEL_WIDTH
HEIGHT = TOPBAR_HEIGHT + BOARD_SIZE + BOTTOMBAR_HEIGHT
